### ISSUE TITLE
Misleading documentation for nudged.Transform#get_matrix()

### ISSUE THREAD

**Issue by mkutny** [axelpale/nudged#10]
Documentation says that `nudged.Transform#get_matrix()` returns affine matrix in the following form (which would be incorrect if it did):

```
|s  -r  tx|
|r   s  ty|
|0   0   1|
```

In fact, the function returns proper matrix (contrary to the doc) which is:

```
|s*cos -s*sin  tx|
|s*sin  s*cos  ty|
|0      0      1|
```

**Comment by axelpale** [comment]
Thanks for the feedback! Could you point out the location in the docs? Because, I can only find [this](https://github.com/axelpale/nudged#nudgedtransformgetmatrix) and for me it seems to be okay.

The method `getMatrix` should return an object:

```
{
    a: ...
    b: ...
    c: ...
    d: ...
    e: ...
    f: ...
}
```

However, the variables `s` and `r` are somewhat misleading, because they are intended to **not** represent scaling and rotation, but `s = lambda * cos(theta)` and `r = lambda * sin(theta)` instead. What do you think, is this the one that might confuse the reader?

**Comment by mkutny** [comment]
Hi Akseli,

I was talking about this [part](https://github.com/axelpale/nudged#nudgedtransforms-r-tx-ty) but actually it rephrases that piece you mentioned in your previous comment.

You're right, I confused `s` and `r` for scaling and rotation.

I'm sure use of expanded expression would make it more obvious. Moreover I'd write `s * cos(theta)` instead of `lambda * cos(theta)` as former notation is quite widespread (take for example the second answer from [this forum](http://math.stackexchange.com/questions/237369/given-this-transformation-matrix-how-do-i-decompose-it-into-translation-rotati)).

**Comment by axelpale** [comment]
Thanks for the clarification. I think you are right, the part should be documented better. I will look into it.

The symbols `s` and `r` are used throughout in the source and also in [the thesis](http://dspace.cc.tut.fi/dpub/handle/123456789/24173) that led to the development of `nudged`. Although `s` and `r` are easily confused with scaling and rotation, I need to keep these three pieces of work consistent. Nevertheless, the docs should be improved to make it more clear.

Thank you. Let me know if you have any problems or questions regarding the lib and its use.
